# Generated by Django 5.2.7 on 2025-11-03 00:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('OFFICE_SUPPLIES', 'Office Supplies'), ('TRAVEL', 'Travel'), ('MEALS', 'Meals & Entertainment'), ('SOFTWARE', 'Software & Subscriptions'), ('EQUIPMENT', 'Equipment'), ('MARKETING', 'Marketing & Advertising'), ('PROFESSIONAL_SERVICES', 'Professional Services'), ('UTILITIES', 'Utilities'), ('RENT', 'Rent'), ('INSURANCE', 'Insurance'), ('TAXES', 'Taxes'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('expense_date', models.DateField()),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('notes', models.TextField(blank=True)),
                ('vendor', models.CharField(blank=True, help_text='Vendor or payee name', max_length=255)),
                ('tax_deductible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
