# Generated by Django 5.2.7 on 2025-11-03 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', '-created_at'], name='clients_cli_user_id_ebd3f8_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'email'], name='clients_cli_user_id_97743a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('user', 'email')},
        ),
    ]
