# Generated by Django 5.2.7 on 2025-11-03 00:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('PAYPAL', 'PayPal'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction reference', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['invoice', '-payment_date'], name='payments_pa_invoice_679b41_idx'), models.Index(fields=['-payment_date'], name='payments_pa_payment_60e7bc_idx')],
            },
        ),
    ]
